apiVersion: v1
kind: Pod
metadata:
   name: flipkart
spec:
   containers:
     - name: signup
       image: centos
       command: ["/bin/bash", "-c", "sleep 10000"]
       volumeMounts:
         - mountPath: /tmp/hostpath
           name: amit
   volumes:
     - name: amit
       hostPath:
         path: /tmp/data
